# Generated by Django 6.0.4 on 2026-04-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('entradas', models.PositiveIntegerField(default=0)),
                ('salidas', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
